### ISSUE TITLE
Problematic database entries for certain games and software

### ISSUE THREAD

**Issue by wickles** [Theo47/depressurizer#10]
I have some games and software with named but unpopulated database entries and thus no tags, genre, flags etc. Several issues at play here. 

First is that some games show one appID in the database, but clicking through to the store page redirects to another ID. Examples are 
- Serious Sam HD: The Second Encounter. Shows as 41010 in DB but 41014 in store
- Grand Theft Auto: III / Vice City / San Andreas. These actually appear twice, I guess because they have mac versions listed separately? I only noticed GTA VC at first because it was the only one that redirected to the correct store page from my games list. 

Second is that Source Filmmaker doesn't have any information in the DB entry, but it has the correct appID. Maybe it doesn't work for any software? Doesn't work for Star Swarm Stress Test either, but these are the only two software I have on Steam. 

BTW, should I be filing issues here for depressurizer in general? Or only for bugs with your updates? Do you have control over issues for rallion's? I think he's active on reddit if you want to get in touch with him, btw.

**Comment by wickles** [comment]
A few more for you. 
- Red Orchestra 2: Heroes of Stalingrad - Single Player (This one is split into a few components in library)
- FEAR: Extraction Point; and FEAR: Perseus Mandate (These are DLCs/expansions for FEAR so they don't have their own page and might be listed oddly within Steam?)
- Deus Ex: Human Revolution (this one is just delisted in favor of the director's cut)

In these cases there is no store page for the specific ID, but they are each associated with some other game on Steam.

**Comment by Theo47** [comment]
According to steamdb, Serious Sam HD: The Second Encounter is [41010](https://steamdb.info/app/41010/) while [41014](https://steamdb.info/app/41014/) is the "Second Edition Full Game" DLC for it which explains why depressurizer recognises the game as 41010.

But since visiting the steam store page for 41010 redirects to 41014 it shouldn't had been an empty entry. The actual reason it is an empty entry seems to be cause depressurizer gets stuck on the age check for the game. Not sure how to bypass it. I'll see if i can figure something out.

**Comment by Theo47** [comment]
You are right about the GTA games. According to steamdb the steam and windows versions are listed as different games with different steam ids and different developers and since depressurizer scrapes steam to get its database they are listed as different games there too.

The interesting thing here is that while the windows versions of the games have entries on the depressurizer database the mac versions are empty. So it seems the age cookie bypasses age check normally but doesn't work if steam redirects you to another page.

**Comment by Theo47** [comment]
Apparently it didn't scrape any software. This was easy to fix though so i already did it.

**Comment by Theo47** [comment]
You can post any issues about depressurizer in general. It doesn't have to be limited to my updates. I have no control over rallion's repository so posting issues here makes it easier for me to manage them since i can just close them once i am done.

I'll take a look at the rest of the games tomorrow.

**Comment by wickles** [comment]
Cool beans, thanks!

**Comment by Theo47** [comment]
FEAR: Extraction Point; and FEAR: Perseus Mandate weren't recognised due to the age check problem fixed above. So now they should be scraped correctly.

The Red Orchestra 2: Heroes of Stalingrad - Single Player DLC has an empty database entry but has a parent listed so if you try to autocategorize it it will use its parents flags/tags/genres instead.

There is no indication in the steam database that Deus Ex: Human Revolution is related to director's cut, or any other game for that matter, so i can't automatically link them. But you can manually add the director's cut as parent in the database though.

Same goes for Red Orchestra 2: Heroes of Stalingrad - Single Player (Game).

**Comment by wickles** [comment]
Ahh -- okay, I was not aware of the 'parent' functionality in the database. Works great, thanks!

**Comment by Theo47** [comment]
I only became aware of it myself 2 days ago ^_^
