### ISSUE TITLE
Error when updating from HLTB

### ISSUE THREAD

**Issue by Drsen57** [Theo47/depressurizer#111]
![screenshot_26](https://user-images.githubusercontent.com/23414140/27520573-5835e64e-59dc-11e7-94a4-bcfe32192bf4.png)

**Comment by R1CH-T** [comment]
Sorry. It's a me-too:

![selection_003](https://user-images.githubusercontent.com/5366679/27696684-331a80de-5cea-11e7-9217-2d5b073ece0d.png)

Please let me know if you need more info. :)

**Comment by SXRWahrheit** [comment]
Looks like the server is down, I just tweeted at them

**Comment by Theo47** [comment]
Since www.howlongtobeat.com didn't offer an api (at least during the time i implemented that feature), i was getting the HTLB data from www.howlongtobeatsteam.com.

That site seems to be down now. I'll wait a few more days just in case the site come backs up. After that i'll have to either disable the HLTB autocat or check alternative options for getting that data.

In the meantime you can disable the error message by going to Tools->Settings and unchecking "Update DB with HTLB data on program start". 

p.s: howlongtobeat.com and howlongtobeatsteam.com are 2 different sites run by different people. howlongtobeatsteam.com was scraping howlongtobeat.com to get the HLTB data. Depressurizer was, in turn, using the api howlongtobeatsteam.com provided.

**Comment by agentmith** [comment]
It might be getting hammered from the Steam sale and taken down on purpose until things calm down. I'd wait a while after the sale is over if you don't hear anything back from the dev.

**Comment by Theo47** [comment]
Guess you were right. Page is up again.
