### ISSUE TITLE
Error message: "The output char buffer is too small to contain the decoded characters"

### ISSUE THREAD

**Issue by r6d2** [Theo47/depressurizer#34]
I'm getting the following diagnostics every time I run Depressurizer:

`Updating database from AppInfo...Error updating database from AppInfo: The output char buffer is too small to contain the decoded characters, encoding 'Unicode (UTF-8)' fallback`

Not sure on which version it started to happen, but at least on the current one and the previous one. It does not seem to be critical since the auto categorize runs in spite of this message (with the tolerant check-box set).

When running the interactive version I get a window with the same error, which I must close to continue.

Any help or orientation would be appreciated.

Thanks!

**Comment by Theo47** [comment]
When you say interactive version you mean when you launch the program normally, instead of using automode right?

Can you upload your AppInfo.vdf file? It would help to locate the problem. It is located at Steam\appcache\AppInfo.vdf

In the meantime you can uncheck "Update DB from local files" on automode helper and the "Update DB with AppInfo on program" start option on Tools/Settings. This should stop those messages from appearing.

**Comment by BuBByAU** [comment]
Also get error on startup and while running:


The output char buffer is too small to contain the decoded characters, encoding 'Unicode (UTF-8)' fallback 'System.Text.DecoderReplacementFallback'.
Parameter name: chars
Error encountered when updating database from AppInfo: {0}


[appinfo.txt](https://github.com/Theo47/depressurizer/files/165175/appinfo.txt)

**Comment by Theo47** [comment]
Apparently the problem is caused by games like [Mold on Pizza](http://store.steampowered.com/app/387870/) that have an icon as part of their names.

I didn't even know that was possible before.

I'll see what i can do about that.

**Comment by Theo47** [comment]
Fixed. d0ffc4e1371266fd0ef0328141d3821bc2f869fb
