### ISSUE TITLE
Virus Notifications on Actions (Symantec)

### ISSUE THREAD

**Issue by live4truths** [Theo47/depressurizer#35]
Viewing Games in a list Triggered the following Antivirus cleanup:
[http://securityresponse.symantec.com/security_response/writeup.jsp?docid=2004-091516-5119-99&vid=23588](http://securityresponse.symantec.com/security_response/writeup.jsp?docid=2004-091516-5119-99&vid=23588)

Found inside \gamebanners\xxxxx.jpg &
Internet browser temporary file cache

Attempting to sort or viewing games in list triggered the following:
[http://securityresponse.symantec.com/security_response/writeup.jsp?docid=2004-091516-5119-99&vid=23588](http://securityresponse.symantec.com/security_response/writeup.jsp?docid=2011-022413-0627-99&tabid=2)

Found on depressurizer.exe
Internet browser temporary file cache
\game banners\xx.jpg *

The second trigger is likely the AV thinking something malicious is occurring.

Thank you.

**Comment by Theo47** [comment]
Sounds like a false positive. It detects one of the game banners as malicious.

> Bloodhound.Exploit.13 is a heuristic detection for **malformed JPEG** files. The files detected as Bloodhound.Exploit.13 may be malicious, or they **may be the result of corruption**

Maybe one of the banners got corrupted while downloading which triggered the alert.

Need some additional information:
Was it multiple images or just one?
Did it say which image/s was? Or did it just say xxxxx.jpg?
Is it the same banners each time or do they change?
If they change can you check if an image previously detected as malicious is now getting downloaded properly?
If they remain the same then can you visit https://steamcdn-a.akamaihd.net/steam/apps/400/capsule_sm_120.jpg and download the banner manually? See if you still get an alert. Replace **400** with the id of the banner giving the false positive(the number before .jpg).

The second alert seems to be a result of the first. Since depressurizer keeps downloading images detected as malicious, the heuristic decides that it must be malicious too.

**Comment by live4truths** [comment]
Theo:

It was all game banners on download, i used xxx.jpg to reference it didn't matter what the file was. It is difficult to determine if its the same or if they change, since the AV decides to eat t hem all then list them, but it seems to be the same (based on library images). It occurs every time, so I do not believe its corruption.

Saving the image you linked below did not trigger the action from the AV client. Changing the number to one listed did not trigger the AV client.

It is likely a false positive,  but I believe the AV is acting like it's malicious based on what it's doing/downloading/parsing. the Bloodhound.Exploit.13 occurs first, after attempting to load the library images. Then it decides to eat the executable itself for doing the actions.

Please let me know if I can be of further assistance.

**Comment by Theo47** [comment]
I downloaded Norton Security but i didn't get any alerts while running Depressurizer.

At this point i'd recommend upgrading your antivirus and virus definitions to the latest version if you haven't already.

Also since the alert mentioned corruption consider checking your hard disk for errors.

If the problem still persists you can exclude the depressurizer folder from scanning.

**Comment by live4truths** [comment]
This was with the Symantec Endpoint Protection (Enterprise class) and picked up by the Enterprise "Sonar", not sure if the basic levels have those features.

They are fully updated, but all systems I have tested with on this AV have the problem, so I believe it not to be computer specific. When I remove SEP and try another vendor, the issue goes away. May be prudent to submit your files to Symantec, if you want. 

Let me know if I could be any further assistance.

**Comment by KamiYamabushi** [comment]
This is what Microsoft Defender detects it as: https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fFethar.B!plock&threatid=2147708975&enterprise=0

No info otherwise though.

**Comment by Theo47** [comment]
From a quick [virus scan](https://www.virustotal.com/en/file/02a6e2c4dde27cd91c2b1941450bf63d8389d477030e4be3e1487fc5d3192204/analysis/1488976773/) it looks clean now so i am going to close this.
