### ISSUE TITLE
Category Selection on Automatic Mode

### ISSUE THREAD

**Issue by Theo47** [Theo47/depressurizer#5]
Add ability to select only specific categories to categorize on automatic mode instead of your whole game library.

**Comment by caballinger** [comment]
This feature would be particularly helpful to me right now. However, rather than select categories for automatic mode, I was thinking it might be better for each auto-cat profile to have a list of categories to run on (and set the default to all). The use-case I have in mind is this:

I have 2000+ games, and the Adventure/Action/Indie categories typically have 1000+ games assigned to them, making them basically worthless. HOWEVER, there are some games that ONLY have Adventure/Action/Indie as a category, so I need to keep them around, but it makes those games harder to find amongst 1000+ games. Additionally, some games have tags which are basically the same thing (e.g. Funny / Comedy), and need to be merged.

If each auto-cat can configure which currently-existing categories to run on, I can do the following:
Auto-cat 1: All genres (except Adventure/Action/Indie) on all games
Auto-cat 2: All tags (except Adventure/Action/Indie) on all games
Auto-cat 3: ONLY Adventure/Action/Indie genres on UNCATEGORIZED games
Auto-cat 4: ONLY "Comedy" tags on "Funny" categorized games

By running Auto-cat 1-4 sequentially, I can categorize games based on most of their tags/genres, while thinning out "overcrowded" categorizes so they only contain games that have no better options. It also merges the Comedy and Funny tags, so the redundant tag can be removed.

Now, running 4 auto-cats every time I want to update my library would only be a slight nuisance. But in addition to this feature, it might be a good idea to add another enhancement: Auto-cat macros. Basically, just an auto-cat that runs a list of other auto-cats. So with 1 button press, Auto-cats 1-4 would run in the order I list them in the macro.

I think this solution might be a bit more robust than changing how automatic mode works. It allows for slightly more complex categorization rules (depending on what you originally had in mind, maybe I misunderstood), can be implemented to work with automatic mode (including auto-cat macros), and will work in the GUI for users intimidated by using the command-line for automatic mode. 

I'm not sure idea would be easier to implement yet (probably just changing automatic mode tbh), but I'd be happy to work on either in my spare time (mostly just saturday, and sometimes Sunday), so let me know what you're thoughts are!

**Comment by Theo47** [comment]
As a sidenote you can also access Automode using Tools->Automode Helper which allows you to create a shortcut using the gui.

Personally i autocategorize only uncategorized games instead of all games so automode was useless for me. This was meant to rectify that although i hadn't thought out the specifics.

My current autocat routine is:
1: delete all autocat categories.
2: Autocat uncategorized games by score.
3. Autocat positive+ games by tags and hltb time

>But in addition to this feature, it might be a good idea to add another enhancement: Auto-cat macros. Basically, just an auto-cat that runs a list of other auto-cats. So with 1 button press, Auto-cats 1-4 would run in the order I list them in the macro.

@EnemyWithin is working on something similar. You can now run multiple autocats at once although you can't specify the order they run.
You can also just select the category name instead of having to select all games in that category when autocategorizing which saves some clicks.

I'd suggest taking a look at his build first and decide what still needs to be done.

**Comment by caballinger** [comment]
Thanks for the info, I'll be sure to take a look at his branch!

**Comment by EnemyWithin** [comment]
> Auto-cat 1: All genres (except Adventure/Action/Indie) on all games
Auto-cat 2: All tags (except Adventure/Action/Indie) on all games
Auto-cat 3: ONLY Adventure/Action/Indie genres on UNCATEGORIZED games
Auto-cat 4: ONLY "Comedy" tags on "Funny" categorized games

Checkout my latest dev branch.  I have added saving/loading Filters, as well as applying filters to Autocats.  You should be able to do the above now.

Although you can't reorder Autocats, they are sorted and get applied alphabetically.  Name them appropriately to get the order you desire.

**Comment by caballinger** [comment]
Thanks @EnemyWithin, that is EXACTLY what I was looking for! However, I just realized that my "Auto-cat 4" case (Take everything categorized as "Funny" and apply the "Comedy" tag to it, even if the game does not have the comedy tag) isn't possible with the current auto-cat types. Maybe it would be useful to add a new "Apply Category" auto-cat type. It would take three things: 1) A filter, 2) An action (Add or Remove Categories), and 3) A list of category check-boxes to apply/remove. This would make my auto-cat 4 scenario possible, as well as enabling users to clear out the empty/merged categories.

It would also allow the user to "save the state" of the uncategorized games (or any other category) if they wanted to apply multiple auto-cats to the same set games. To modify my previous example, suppose I added:
Auto-cat 3.5: ONLY Casual Tags on UNCATEGORIZED games
This auto-cat would be disrupted by auto-cat 3, since games caught by auto-cat 3 would no longer be uncategorized.

However, with an add/remove auto-cat. I could add the following:
Auto-cat 2.5: Add "Temp" Category on uncategorized games.
Auto-cat 3.75: Remove "Temp" Category on all "Temp" Category games.

And by changing the filter on Auto-cat 3 and 3.5 to "Temp" instead of "uncategorized", both filters can be applied to the same remaining set of uncategorized games.

**Comment by EnemyWithin** [comment]
I just committed a new version with AutoCatManual.  It should accomplish what you are looking for.  Let me know how it goes.

**Comment by caballinger** [comment]
That works perfectly, thanks again! The only thing preventing me from using your features now is the bugfix Theo made for manually edited DB entries being overridden by null data.

**Comment by Theo47** [comment]
Added. 32f97aad253b704389ae635e7c36f70eebcce276
