### ISSUE TITLE
General slowness when adding categories

### ISSUE THREAD

**Issue by thefunkygibbon** [Theo47/depressurizer#54]
Hi, ok an example
Category <All>
Highlight all in main window 
Tick (or untick, its just as slow) one of the cats to add all games (1500 in my case) to this group (in my case, adding all to an "all games" group.
in 0.6.x it took a few seconds, 
in 0.7.1.1 it is taking over a minute with the app seemingly freezing.

**Comment by thefunkygibbon** [comment]
Also slowness when changing the categories list on the left,  changing the view to a diff list of games freezes up for a long amount of time.  not as bad as when making changes, but still makes for a poor experience.

**Comment by thefunkygibbon** [comment]
Maybe it is quicker on an SSD.  I'm guessing that the images are playing a part in the slowness. I cannot see a way of disabling these within the app.  Are they being read from a cached file on the same location as the .exe or are they read from the image files within the steam folder?

**Comment by Theo47** [comment]
The images are being read from a cached file in the same location as the exe. The caching happens the first time you run the program though so that could explain an initial slowdown. 
Try leaving the program running for a few minutes then check again to see if it has gotten any better.
This won't remove the slowdown when adding/removing categories entirely but it should bring it down the few seconds you were experiencing in the previous versions too.

**Comment by Theo47** [comment]
It should be faster now.
